# Per-stage content for BUILD_PLAN.md (hand-written). Substage file lists come from the patches.

STAGES = {
"01": dict(
 title="Project setup",
 goal="A buildable, empty Compose app with a version catalog, the Gradle wrapper and the launcher icon.",
 test=["Android Studio: **File → Sync Project with Gradle Files** succeeds (decline any AGP upgrade prompt).",
       "Run on the tablet: a dark screen with the text **The Feline Co.**",
       "Home screen of the tablet shows the crimson crown-cat launcher icon."],
 shots=[("S01", "Android Studio with the project open and the first run on the tablet (\"The Feline Co.\" text)."),
        ("S02", "Tablet home screen showing the crown-cat launcher icon.")],
 decisions=["Version catalog (`gradle/libs.versions.toml`) keeps every dependency version in one place.",
            "minSdk 26: needed for `java.time` and adaptive icons; covers almost all active devices. targetSdk 35.",
            "Gradle heap capped at 2 GB because the dev machine has 8 GB RAM and Android Studio runs alongside.",
            "Launcher icon is a vector adaptive icon (no PNG densities to maintain)."],
 issues=["Gradle heap: 4 GB was too much for an 8 GB Mac running Android Studio → reduced to 2 GB in `gradle.properties`."],
 prompts=[("gradle/libs.versions.toml", "Explain how a Gradle version catalog works. How do I reference `androidx-core-ktx` from `app/build.gradle.kts`, and why do newer Android Studio templates use catalogs?", "Explanation"),
          ("app/build.gradle.kts", "I'm building a Compose app for a Samsung tablet. What minSdk should I choose and what would I lose by going below 26?", "Decision support"),
          ("res/drawable/ic_launcher_foreground.xml", "Here is my adaptive icon foreground (108×108 viewport). Check every shape stays inside the 66 dp safe zone so circular masks don't crop it.", "Review"),
          ("gradle.properties", "My MacBook has 8 GB RAM and Gradle builds make it swap. Which Gradle settings should I tune and what are sensible values?", "Troubleshooting")]),
"02": dict(
 title="Brand and design system",
 goal="Colour, typography and shape tokens in a custom Material 3 theme, plus the Canvas-drawn logo, the paw-print motif and a branded splash.",
 test=["Run: splash shows the crown-cat logo, wordmark, progress bar and faint paw prints on onyx.",
       "Open `FelineLogo.kt` → Split/Design view: the logo preview renders.",
       "(Optional) Add the three font files from `ASSETS.md` to `res/font/` and see headlines switch to Playfair Display."],
 shots=[("S03", "Branded splash screen on the tablet (logo, wordmark, paw pattern).")],
 decisions=["Dark-first palette (onyx, charcoal, crimson, silver); light scheme also defined.",
            "Crimson tuned to `#E11D3F` in dark mode so text and white-on-crimson both meet WCAG AA (≈4.1:1 and 4.7:1).",
            "Extra brand colours (success, warning) via a CompositionLocal, because Material 3 has no slots for them.",
            "Fonts looked up by name so the project builds without the font files (falls back to system serif/sans).",
            "Logo drawn on a Canvas: crisp at any size and recolourable, no image assets."],
 issues=["Inside the logo's `Canvas` lambda, `size` referred to the composable's `Dp` parameter, not the draw area (parameters shadow receiver members) → used `this.size` explicitly."],
 prompts=[("ui/theme/Color.kt", "Check the contrast of #E11D3F text on #0E0E10, and of white text on #E11D3F, against WCAG AA. If either fails, suggest the closest shade that passes.", "Accessibility check"),
          ("ui/theme/Theme.kt", "Material 3 has no 'success' or 'warning' colour roles. What's the idiomatic way to add extra brand colours to my theme without hard-coding colours in screens?", "Pattern explanation"),
          ("ui/components/FelineLogo.kt", "Inside my Compose Canvas lambda, `size` seems to be my Dp parameter instead of the canvas size. Why, and what's the cleanest fix?", "Debugging"),
          ("ui/theme/Type.kt", "How can I make custom fonts optional so a teammate can build the project even if they haven't added the .ttf files?", "Design alternatives")]),
"03": dict(
 title="Domain model and business rules",
 goal="Pure-Kotlin models (Parcelable), the credit rules, search/filter/sort queries and form validators, all unit-tested.",
 test=["`./gradlew :app:testDebugUnitTest`: **22 tests pass** after 03.5 (6 after 03.3, 14 after 03.4).",
       "In Android Studio: right-click `app/src/test/java` → Run, and check the green tree."],
 shots=[("S04", "Android Studio Run window showing the 22 domain unit tests passing.")],
 decisions=["Business rules live in plain Kotlin (`domain/`) so they can be tested without a device.",
            "`@Parcelize` for Cat, Booking, CartItem, Order (needed later for Intents).",
            "Age groups as an enum with month ranges and no gaps; fees derived from age, never stored.",
            "`CatQuery` is plain data plus a pure `apply()` function, which makes filtering trivially testable.",
            "Validators return an error message or null: simple to show inline and to test."],
 issues=["Computed `get()` properties in a `@Parcelize` class were annotated `@IgnoredOnParcel`, which gives a warning; it isn't needed because they have no backing field → removed.",
         "Date validation depended on 'today', which made tests flaky → `today` is passed in as a parameter."],
 prompts=[("domain/CreditRules.kt", "My rules: kittens under 6 months cost 150 credits, 6–23 months 100, two years and over free, and each completed adoption earns 250. List the edge cases I should unit-test, especially at the age boundaries.", "Test design"),
          ("domain/model/Cat.kt", "What's the difference between @Parcelize and writing Parcelable by hand? Why don't computed `get()` properties need @IgnoredOnParcel?", "Explanation"),
          ("domain/CatQuery.kt", "Review my filter-and-sort function. Is a Sequence worthwhile for about 25 items? Suggest clearer comparators for 'oldest first' with a name tie-break.", "Code review"),
          ("domain/validation/Validators.kt", "Write JUnit tests for these validators, including Australian phone numbers with spaces and a date rule where Mondays are closed. Explain each case.", "Test generation (verify every case!)")]),
"04": dict(
 title="Reusable UI components",
 goal="The component library every screen will use: badges and status chips, empty/loading states, validated fields, name-based images, cat and product cards, and previews.",
 test=["Build succeeds.", "Open `ui/components/ComponentPreviews.kt` → Split view: cat cards, product cards and badges render (photos show the branded placeholder)."],
 shots=[("S05", "Android Studio Design pane showing the component previews (cat cards, product cards, badges).")],
 decisions=["Stateless components that take a `modifier`, so screens control layout.",
            "Photos looked up by file name: missing photos show a crimson placeholder instead of breaking the build; `res/raw/keep.xml` stops the resource shrinker removing them.",
            "Coil loads and downsamples large photos, keeping memory low on the tablet.",
            "A dark gradient scrim under text on photos guarantees readable labels.",
            "Cat cards merge their semantics into one TalkBack description (name, breed, age, sex, fee)."],
 issues=["Optional composable slots built with `?.let { { … } }` can be inferred as non-composable lambdas → declared explicit `(@Composable () -> Unit)?` values.",
         "`Resources.getIdentifier` triggers a 'discouraged API' lint warning → suppressed with a comment explaining why it's deliberate."],
 prompts=[("ui/components/AssetImage.kt", "I want to show photos from res/drawable by file name so missing files don't break the build. What are the downsides of Resources.getIdentifier, and how do I stop R8 removing those images?", "Trade-off analysis"),
          ("ui/components/FormFields.kt", "Refactor my OutlinedTextField wrapper so error text, helper text and the error icon are handled in one stateless, reusable composable.", "Refactoring"),
          ("ui/components/CatCard.kt", "How should TalkBack read this card? Suggest a contentDescription that combines name, breed, age, sex and fee and skips the decorative image.", "Accessibility"),
          ("ui/components/ComponentPreviews.kt", "Write @Preview functions for CatCard and ProductCard showing a free cat, a pending cat and an out-of-stock product.", "Boilerplate generation")]),
"05": dict(
 title="Local database (Room)",
 goal="Room entities, mappers, DAOs, the database class, password hashing, the credit ledger helper and seed data.",
 test=["Build succeeds (KSP generates the Room code).",
       "After 05.3 a schema file appears at `app/schemas/com.thefelineco.data.local.FelineDatabase/1.json`: include it in that commit (`git add -A` picks it up)."],
 shots=[("S06", "Android Studio Project view showing the `data/local` packages and the generated `app/schemas/…/1.json`.")],
 decisions=["Separate Room entities from domain models, with extension-function mappers, so the schema can change without touching the UI.",
            "Enums stored by name; a TypeConverter stores personality lists.",
            "Foreign keys with CASCADE for basket and order lines; bookings and order lines keep a snapshot of the name/price so history never changes.",
            "Salted SHA-256 for demo passwords (a production app would use bcrypt/Argon2 on a server).",
            "Destructive migration during development; schema JSON exported for review."],
 issues=["Room 2.6.1 is built for KSP1; newer KSP can switch to KSP2 → pinned `ksp.useKSP2=false`.",
         "Foreign-key child columns need an index or Room warns about full-table scans → added `Index(\"productId\")` / `Index(\"orderId\")`."],
 prompts=[("data/local/entity/Entities.kt", "Should my Room entities be the same classes as my domain models? Give pros and cons for a small app that's marked on code quality.", "Design discussion"),
          ("data/local/dao/ShopDao.kt", "Write a Room @Query that joins cart_items with products into a CartLine data class, and explain how Room matches the column aliases to properties.", "Code + explanation"),
          ("data/local/PasswordHasher.kt", "Is salted SHA-256 acceptable for demo passwords in a local-only student app? What would a production app use, and why?", "Security review"),
          ("build output", "KSP error: 'ksp-2.1.0-1.0.29 is too new for kotlin-2.0.0'. What does this mean and how do I align the versions in libs.versions.toml?", "Debugging")]),
"06": dict(
 title="Repositories and app container",
 goal="Repositories with transactional credit operations, the DataStore session and settings, manual DI, first-launch seeding and instrumented tests.",
 test=["Run the app (still shows the splash). Then **App Inspection → Database Inspector** → `feline.db`: `cats` has 24 rows, `products` 18, `users` 2.",
       "Tablet connected: `./gradlew :app:connectedDebugAndroidTest`; all `AdoptionAndShopFlowTest` tests pass."],
 shots=[("S07", "Database Inspector showing the seeded `cats` table."),
        ("S08", "Instrumented test results (AdoptionAndShopFlowTest) passing on the tablet.")],
 decisions=["Repositories are interfaces, so ViewModel tests can use in-memory fakes.",
            "Multi-step operations (book, cancel, complete, checkout) run inside `withTransaction`.",
            "Every balance change goes through `recordCredits`, so the balance and the wallet history always agree.",
            "The adoption fee is held at booking and refunded on cancel or decline.",
            "DataStore instead of SharedPreferences; manual DI (`AppContainer`) instead of Hilt."],
 issues=["`@Upsert` returns -1 when it updates an existing row → map back to the existing id.",
         "Seeding runs on app start in the background; a very fast first login could race it (the seed takes milliseconds, so this was accepted and noted)."],
 prompts=[("data/repository/BookingRepository.kt", "Walk through requestBooking and tell me what could go wrong if two people book the same cat at the same moment. Does withTransaction fully protect me?", "Concurrency review"),
          ("di/AppContainer.kt", "Compare manual dependency injection with Hilt for a single-module student app. Which is easier to explain in a report, and what do I give up?", "Decision support"),
          ("data/repository/SessionStore.kt", "Why does Google recommend DataStore over SharedPreferences? Show how to expose a stored user id as a Flow.", "Explanation"),
          ("androidTest/.../AdoptionAndShopFlowTest.kt", "Suggest instrumented tests proving credits are held on booking, refunded on cancel and rewarded on adoption, using an in-memory Room database.", "Test design")]),
"07": dict(
 title="Sign in and registration",
 goal="Shared activity theme helper, session/login/register ViewModels, the login and register screens, the session switch and a Compose UI test.",
 test=["Run: login screen (photo panel + form on the tablet).",
       "Tap **Sign in** empty → field errors. Wrong password → red banner.",
       "**Create an account** → submit empty → every field errors; register a new user → signed in with 200 credits.",
       "Tap **Customer** demo → \"Signed in as Jordan Demo · 400 credits\"; **Log out** works; close and reopen → still signed in.",
       "`./gradlew :app:connectedDebugAndroidTest`: `LoginScreenTest` passes."],
 shots=[("S09", "Login screen on the tablet (photo brand panel + form)."),
        ("S10", "Register screen showing validation errors.")],
 decisions=["Unidirectional data flow: immutable `UiState` + sealed `Event` interface per form.",
            "A field's error clears as soon as it's edited (don't nag while typing).",
            "One-tap demo accounts so markers can test both roles quickly.",
            "`AnimatedContent` keyed by account cross-fades between splash, sign-in and app.",
            "`setFelineContent()` gives every activity the same theme and edge-to-edge system bars."],
 issues=["Compile error: `maxHeight` from `BoxWithConstraints` couldn't be read inside a nested `Column` (Compose layout scopes are DSL-marked) → read it into a local `val` first.",
         "`AnimatedContent` kept a stale snapshot of the user, so the credit balance wouldn't update → read the latest session state instead of the captured one.",
         "On phones the form added a second status-bar gap under the photo banner → only apply the top inset when the form isn't below the banner."],
 prompts=[("ui/auth/AuthViewModels.kt", "Review my LoginViewModel. Is a sealed LoginEvent interface overkill for four events? What does it buy me in testing and readability?", "Code review"),
          ("ui/auth/AuthLayout.kt", "Compile error: \"'val maxHeight: Dp' cannot be called in this context with an implicit receiver\" inside a Column nested in BoxWithConstraints. Why, and how do I fix it?", "Debugging"),
          ("ui/auth/FormErrorBanner.kt", "When my login fails I show 'Incorrect email or password'. How do I make TalkBack announce it automatically?", "Accessibility"),
          ("androidTest/.../LoginScreenTest.kt", "Write a Compose UI test for my stateless LoginContent that checks errors are displayed and that the demo buttons send the right events.", "Test generation")]),
"08": dict(
 title="Adaptive app shell and navigation",
 goal="Top-level destinations, the adaptive shell (navigation rail on tablets, bottom bar on phones), the NavHost with placeholder screens, and the final MainActivity.",
 test=["Customer demo: a rail on the left with Home, Adopt, Shop, Basket, Bookings, Account; tapping each shows its placeholder; the selected item is highlighted.",
       "Account placeholder → Log out works.", "Admin demo: the rail shows Dashboard, Cats, Appointments, Products, Account.",
       "Rotate to portrait / try a phone emulator: a bottom bar appears instead of the rail."],
 shots=[("S11", "App shell with the navigation rail on the tablet (customer).")],
 decisions=["Type-safe `@Serializable` routes instead of string routes: arguments are compile-time checked.",
            "`NavigationSuiteScaffold` picks a rail or a bar by width (≥600 dp → rail).",
            "Top-level navigation uses `popUpTo(start){saveState}` + `restoreState` so each tab keeps its scroll position.",
            "Customers and admins get different destination sets in the same app.",
            "A temporary `ComingSoonScreen` keeps every destination runnable until it's built."],
 issues=["The bottom bar already pads for the system navigation bar but the rail doesn't, so content was hidden behind the gesture bar on tablets → add navigation-bar padding only in rail mode."],
 prompts=[("ui/navigation/Routes.kt", "Explain type-safe Navigation Compose routes with @Serializable. How do I pass a catId and read it in a ViewModel?", "Explanation"),
          ("ui/navigation/FelineAppShell.kt", "My bottom bar pads for the system navigation bar but the navigation rail doesn't. How should I handle WindowInsets so content isn't hidden in either layout?", "Layout debugging"),
          ("ui/navigation/FelineAppShell.kt", "What do saveState and restoreState do when navigating between bottom-navigation tabs, and what bug do they prevent?", "Explanation"),
          ("ui/navigation/TopLevelDestination.kt", "Which top-level destinations should a customer and an admin see? Base it on Material 3's guidance for navigation rails.", "UX advice")]),
"09": dict(
 title="Home",
 goal="The Home dashboard: hero, live stats, new-arrivals carousel, the free-adoption banner, how-it-works steps and shop highlights.",
 test=["Home shows the hero, \"24 cats looking for a home\", new arrivals (newest first), the senior banner, three steps and shop picks.",
       "Credit chip shows 400 for the demo customer.", "Scroll is smooth; on a phone the stat cards hide their icons."],
 shots=[("S12", "Home screen on the tablet.")],
 decisions=["One `HomeUiState` built by `combine()`-ing the user, cats and products flows (`stateIn(WhileSubscribed(5000))`).",
            "The hero stays dark in both themes so its white text is always readable.",
            "Content width is capped at 1280 dp so lines stay readable on large tablets."],
 issues=["In the light theme the hero faded into a pale background right under white text → hero kept dark with rounded bottom corners.",
         "Stat cards were cramped on narrow phones → icons hidden below 600 dp."],
 prompts=[("ui/home/HomeViewModel.kt", "I combine three Flows and call stateIn(viewModelScope, WhileSubscribed(5000), …). What does the 5000 ms do and when do the upstream flows stop?", "Explanation"),
          ("ui/home/HomeScreen.kt", "Critique my Home layout for an 11-inch tablet in landscape against Material 3 large-screen guidance. What would you change first?", "Design critique"),
          ("ui/home/HomeScreen.kt", "White text over a photo hero is hard to read in my light theme. Give three ways to guarantee contrast and their trade-offs.", "Problem solving")]),
"10": dict(
 title="Adopt: search, filter and sort",
 goal="Search field and sort menu, the Adopt ViewModel (with fakes and unit tests), the filter panel and the Adopt screen.",
 test=["Adopt shows a grid of 24 cats with the filter side panel (tablet).",
       "Search `maine` → Willow and Archie. **Free to adopt** → only 2+ cats. Sort **Oldest first** → Olive first.",
       "Over-filter → \"No cats match\" + **Clear filters**. Home → **Browse free-to-adopt cats** opens Adopt with Free selected.",
       "Rotate: filters are kept. `./gradlew :app:testDebugUnitTest` → **26 tests pass**."],
 shots=[("S13", "Adopt screen with the filter side panel."),
        ("S14", "Adopt results filtered and sorted (e.g. Free to adopt + Oldest first).")],
 decisions=["All filter state lives in one `CatQuery` inside the ViewModel; results recompute when the query or the data changes.",
            "Quick chips for common filters + a full panel: permanent side panel ≥840 dp, bottom sheet below.",
            "`Modifier.animateItem()` animates cards as results change (dynamic UI).",
            "The `freeOnly` route argument is read through `SavedStateHandle.toRoute()`.",
            "ViewModel tests use in-memory fake repositories and a `MainDispatcherRule`."],
 issues=["Unit test read `uiState.value` but it never updated: `stateIn(WhileSubscribed)` only runs while collected → tests start a collector in `backgroundScope`.",
         "Quick-chip labels were built by adding \"s\" (\"Youngs\") → proper plural labels per age group."],
 prompts=[("ui/adopt/AdoptViewModel.kt", "My filters live in one CatQuery data class inside a MutableStateFlow. Is that better than a separate StateFlow per filter? Consider testing and recomposition.", "Design review"),
          ("test/.../AdoptViewModelTest.kt", "My test reads uiState.value but it never changes. The ViewModel uses stateIn(WhileSubscribed). Why, and how do I fix it with runTest?", "Debugging"),
          ("ui/adopt/AdoptScreen.kt", "When should filters be a permanent side panel versus a bottom sheet? Base the answer on window size classes.", "UX research"),
          ("ui/adopt/CatFilterPanel.kt", "Write concise KDoc for these filter composables that explains the why, not just the what.", "Documentation")]),
"11": dict(
 title="Cat profile",
 goal="The cat profile ViewModel and screen: photo, story, personality, special care, facts, health, compatibility, fee vs. balance, similar cats.",
 test=["Open Mochi: two panes on the tablet (photo left, details right). Fee 150, balance 400.",
       "Open a senior: fee **Free**. Similar cats row opens other profiles. Back returns to Adopt.",
       "**Book a meet & greet** shows a 'coming soon' snackbar (booking arrives in stage 12)."],
 shots=[("S15", "Cat profile in the two-pane tablet layout.")],
 decisions=["`canBook` / `canAfford` / `creditsShort` are computed in the UiState, not the composable, so they're testable.",
            "When booking isn't possible the card explains why (already reserved, adopted, or short of credits): error prevention.",
            "'You might also love' suggests other available cats in the same life stage."],
 issues=[],
 prompts=[("ui/catdetail/CatDetailViewModel.kt", "Where should the rule 'this user can book this cat' live: the composable, the ViewModel or the domain layer? Justify it for testability.", "Architecture"),
          ("ui/catdetail/CatDetailScreen.kt", "Write the message shown when the booking button is disabled because the user is short of credits, following Nielsen's 'help users recognise, diagnose and recover from errors'.", "UX writing"),
          ("ui/catdetail/CatDetailScreen.kt", "Can I put a LazyRow inside a Column with verticalScroll? When would that crash, and why?", "Explanation")]),
"12": dict(
 title="BookingActivity and the Activity Result API",
 goal="Dialogs and a date strip, the booking ViewModel (with tests), `BookingActivity` with its Parcelable input/output contract, and launching it from the profile.",
 test=["From Mochi → **Book a meet & greet** → BookingActivity opens showing Mochi (Cat passed as Parcelable).",
       "**Confirm booking** empty → errors for day, time, phone, home and terms + banner. Mondays show *Closed*.",
       "Toggle **I have other pets** → a warning appears (Mochi prefers to be the only pet).",
       "Complete and confirm → activity closes → **\"You're booked in!\"** dialog (Booking returned). Credits now 250.",
       "Book another cat for the same day/time → that slot shows *Booked*. Back out of the form → nothing changes.",
       "`./gradlew :app:testDebugUnitTest` → **34 tests pass**."],
 shots=[("S16", "BookingActivity: the meet & greet form on the tablet."),
        ("S17", "Booking form showing validation errors."),
        ("S18", "\"You're booked in!\" confirmation dialog back in MainActivity.")],
 decisions=["A separate Activity as the brief requires, with a custom `ActivityResultContract<Cat, Booking?>` for typed input and output.",
            "`IntentCompat.getParcelableExtra` instead of the deprecated `getParcelableExtra(String)`.",
            "The ViewModel receives the Cat through a small factory in the activity.",
            "A horizontal date strip instead of a calendar dialog: every option is visible and one tap away on a tablet.",
            "Errors are keyed by a `BookingField` enum; the repository re-checks the rules (defence in depth).",
            "The confirmation dialog state is `rememberSaveable` (Parcelable), so it survives rotation."],
 issues=["`Intent.getParcelableExtra(String)` is deprecated from API 33 → `IntentCompat` keeps one code path for API 26–35.",
         "A slot could be taken between picking it and confirming → the repository rejects it and the form refreshes the taken slots."],
 prompts=[("ui/booking/BookMeetAndGreet.kt", "Show me how to write a custom ActivityResultContract that takes a Parcelable Cat and returns a Booking or null. Why is this better than startActivityForResult?", "Explanation + code"),
          ("ui/booking/BookingActivity.kt", "getParcelableExtra(String) is deprecated. What's the backward-compatible replacement when minSdk is 26?", "API migration"),
          ("ui/booking/BookingViewModel.kt", "Review validate(). Does keying errors by an enum make sense, and how do I clear only the edited field's error?", "Code review"),
          ("test/.../BookingViewModelTest.kt", "List the test cases for a booking form with date, time slot, phone, home type and terms, including a slot taken by someone else.", "Test design")]),
"13": dict(
 title="My bookings",
 goal="A reusable booking card and the My Bookings screen with cancel and refund.",
 test=["Bookings tab: the new booking is under **Upcoming** with a *Requested* chip.",
       "**Cancel booking** → confirmation dialog → snackbar \"…credits refunded\"; it moves to **Past**; the cat is available again.",
       "With no bookings: empty state with **Find a cat**."],
 shots=[("S19", "My Bookings with upcoming and past sections.")],
 decisions=["One-off messages (snackbars) go through a `Channel`, not the UiState, so they aren't replayed on rotation.",
            "Destructive actions ask for confirmation and state the consequence (refund, cat released)."],
 issues=["`animateItem()` was unresolved inside a helper's card lambda because the lambda lacked the grid item scope → gave the lambda `LazyGridItemScope` as its receiver."],
 prompts=[("ui/bookings/BookingsViewModel.kt", "Should snackbar messages be part of UiState or a separate Channel? What happens to each on rotation?", "Design trade-off"),
          ("ui/bookings/BookingsScreen.kt", "Error: 'Unresolved reference: animateItem' inside a lambda I pass to my own LazyGridScope extension. Why, and how do I give the lambda the right scope?", "Debugging"),
          ("ui/components/Dialogs.kt", "When should an app ask for confirmation before an action? Give HCI guidance and an example of good confirmation wording.", "UX guidance")]),
"14": dict(
 title="Shop",
 goal="The shop ViewModel, a quantity stepper and the shop screen with categories, sorting and a product sheet.",
 test=["Shop: category chips, search, **Price: high to low**.",
       "Open a product → sheet with description and stock; quantity can't exceed stock minus what's in the basket.",
       "**Add to basket** → snackbar; the **Basket** rail item shows a badge. The out-of-stock slicker brush can't be added."],
 shots=[("S20", "Shop with the product sheet open.")],
 decisions=["Prices are in credits only, tying the shop to the adoption economy.",
            "The sheet remembers the product *id*, not a copy, so stock shown is always live.",
            "The basket badge comes from `MainViewModel`, visible on every screen."],
 issues=[],
 prompts=[("ui/shop/ShopViewModel.kt", "I combine four flows (products, query, user, basket). Is there a limit to combine(), and how do I keep this readable?", "Explanation"),
          ("ui/shop/ShopScreen.kt", "My bottom sheet keeps a Product copy and shows stale stock after an update. How do I keep it live?", "Debugging"),
          ("ui/components/QuantityStepper.kt", "Make my − / + stepper accessible: what content descriptions and touch-target sizes should it have?", "Accessibility")]),
"15": dict(
 title="Basket and CheckoutActivity",
 goal="The basket with live totals, the checkout ViewModel (with tests), `CheckoutActivity` with its Parcelable list contract, and launching it from the basket.",
 test=["Basket: change quantities and remove items; totals, balance-after and the shortfall warning update instantly.",
       "**Checkout** → CheckoutActivity opens with the items (ArrayList of Parcelables).",
       "Standard delivery with no address → address, suburb and postcode errors; letters can't be typed into postcode.",
       "**Click & collect** → address fields slide away. **Place order** → \"Order placed!\" dialog; basket empty; credits reduced; stock reduced.",
       "`./gradlew :app:testDebugUnitTest` → **40 tests pass**."],
 shots=[("S21", "Basket with order summary."),
        ("S22", "CheckoutActivity with the delivery form."),
        ("S23", "\"Order placed!\" dialog back in MainActivity.")],
 decisions=["The basket goes to the activity as `ArrayList<CartItem>`; the placed `Order` comes back as a Parcelable result.",
            "Checkout re-reads prices and stock from the database rather than trusting the basket passed in.",
            "Conditional validation: address fields only for delivery methods that need them.",
            "Input filtering: postcode keeps digits only (max 4)."],
 issues=["Stock can drop after an item was added to the basket → over-stock warning on the line and a guard at checkout."],
 prompts=[("ui/checkout/CheckoutContract.kt", "How do I pass a List of Parcelables through an Intent and read it back safely on API 26–35?", "Explanation"),
          ("ui/checkout/CheckoutViewModel.kt", "Address fields are only required for delivery, not click & collect. What's a clean way to express conditional validation?", "Design"),
          ("data/repository/ShopRepository.kt", "Why should checkout re-read prices and stock from the database instead of trusting the basket the screen passes in?", "Robustness review"),
          ("test/.../CheckoutViewModelTest.kt", "Write tests showing express delivery adds 10 credits and that the order is blocked when the balance is too low.", "Test generation")]),
"16": dict(
 title="Account, wallet and theme",
 goal="The account ViewModel and screen: profile card, credit wallet history, orders and the dark/light theme setting.",
 test=["Account: balance, earned/spent, wallet history (welcome bonus, demo bonus, fee held, refund, purchase) and the Orders tab.",
       "Switch **Dark theme** off → the whole app, including the Booking and Checkout activities, turns light. Restart → the setting is remembered.",
       "Admin account: profile and settings only (no wallet)."],
 shots=[("S24", "Account screen with the wallet history (dark theme)."),
        ("S25", "The app in the light theme.")],
 decisions=["Theme choice stored in DataStore and applied by the shared `setFelineContent()` in all three activities.",
            "The wallet is a ledger of `CreditTransaction`s, so the balance is always explainable."],
 issues=["On tablets the history list overflowed under the tabs (a `Column` gives each child the full height) → `Modifier.weight(1f)` on the list."],
 prompts=[("ui/common/FelineContent.kt", "My three activities each call setContent. How can they share one theme and follow a dark/light setting stored in DataStore?", "Refactoring"),
          ("ui/profile/ProfileScreen.kt", "My LazyColumn under a TabRow cuts off the last items on a tablet. Why does the Column give it the full height?", "Debugging"),
          ("ui/profile/ProfileViewModel.kt", "Is it fine to compute totals like 'earned' and 'spent' as computed properties on the UiState?", "Review")]),
"17": dict(
 title="Admin",
 goal="Admin components, dashboard, listing management, the cat form, appointments management, and product management (the placeholder screen is removed at the end).",
 test=["Admin demo → Dashboard: stats, new requests (Confirm/Decline), low stock.",
       "Cats: search, status chips with counts. **Add cat** → Save empty → errors; image name `Cat-Luna` → resource-name error; age 0 y 3 m → fee preview 150.",
       "Save → snackbar, back on the list; the new cat appears for customers too. Delete a cat with an active booking → blocked with a message.",
       "Appointments: Requests / Confirmed / Adopted / Closed tabs; **Complete adoption** → confirmation → customer gets +250 (check by signing in as the customer).",
       "Products: stock stepper; out-of-stock items become available in the shop; product form validation."],
 shots=[("S26", "Admin dashboard."),
        ("S27", "Cat form showing validation errors and the live fee preview."),
        ("S28", "Appointments with the 'Complete adoption' confirmation.")],
 decisions=["Same app, role-based destinations; *Pending* is only ever set by a booking, so the form offers just Available/Adopted.",
            "Number fields are kept as text while typing and parsed on save.",
            "Image names are validated against Android resource rules, with a live preview.",
            "Credit-changing admin actions (decline, complete) ask for confirmation."],
 issues=["A snackbar launched from a form that's being popped never showed (its coroutine scope was cancelled) → the message is shown from a NavHost-level scope.",
         "Deleting a cat with an active booking would orphan held credits → the repository blocks it with a clear message."],
 prompts=[("ui/admin/CatFormViewModel.kt", "Should numeric form fields be stored as String or Int in the UiState? What happens while the user is mid-typing?", "Design"),
          ("ui/navigation/FelineNavHost.kt", "My snackbar doesn't show after popBackStack() from a form screen. Why is the coroutine cancelled, and where should it be launched?", "Debugging"),
          ("ui/admin/AdminBookingsScreen.kt", "Suggest a status-filter design for an admin appointments list (requests, confirmed, adopted, closed) and how to show counts.", "UX"),
          ("ui/admin/AdminComponents.kt", "Write a regex for valid Android resource file names and explain each part.", "Code + explanation")]),
"18": dict(
 title="Extra feature: favourites",
 goal="Per-user favourites stored in Room (database version 2), a favourites filter, an animated heart, and favourites on Adopt, profiles and Home.",
 test=["Heart two cats → hearts pop red; the **♥ Favourites (2)** chip filters to them; Home shows **Your favourites**.",
       "Un-heart → it disappears immediately. Restart → favourites persist. A different account has its own favourites.",
       "Unit tests → **42 pass**; instrumented `favouritesToggleAndAreRemovedWithTheCat` passes."],
 shots=[("S29", "Adopt with hearted cats and the Favourites filter active.")],
 decisions=["`favourites` table with a composite primary key (userId, catId) and a CASCADE foreign key to cats.",
            "Cats are saved with `@Upsert` (insert-or-update) rather than REPLACE, so editing a cat never cascades away favourites.",
            "Shared helpers (`favouriteIds`, `toggleFavourite`) avoid repeating the same flow logic in three ViewModels."],
 issues=["`REPLACE` conflict strategy deletes and re-inserts the row, which would trigger the cascade and wipe favourites → verified that `@Upsert` updates in place (instrumented test).",
         "Bumping the database version wiped existing data (destructive migration) → acceptable in development; a real release would need a `Migration`."],
 prompts=[("data/local/entity/Entities.kt", "Design a Room table for per-user favourite cats with cascade delete. What should the primary key be?", "Schema design"),
          ("data/local/dao/CatDao.kt", "Will OnConflictStrategy.REPLACE on my cats table trigger ON DELETE CASCADE on a favourites table? How can I prove it with a test?", "Investigation"),
          ("ui/components/CatCard.kt", "Add a subtle 'pop' animation to a heart icon when it's toggled, using animateFloatAsState with a spring.", "Code generation"),
          ("data/local/FelineDatabase.kt", "I bumped my Room version and my test data disappeared. Explain fallbackToDestructiveMigration and when I'd need a real Migration.", "Explanation")]),
"19": dict(
 title="Documentation, final testing and submission",
 goal="README and the testing guide; a full manual test pass on tablet and phone; final worklog sections.",
 test=["Run the whole `TESTING.md` script on the tablet; rotate on key screens; try a phone emulator; quick TalkBack pass on a cat card.",
       "`./gradlew :app:testDebugUnitTest` (42 pass) and `./gradlew :app:connectedDebugAndroidTest` (all pass).",
       "Fill in §5 Testing Summary, §6 Reflection, the time totals, the references (image credits) and the screenshot index."],
 shots=[("S30", "The app on a phone-sized screen (bottom navigation bar).")],
 decisions=["The README is written for a marker with five minutes: features, architecture, how to run, demo accounts, tests.",
            "The manual test script is mapped to the brief's topics."],
 issues=[],
 prompts=[("README.md", "Review my README as if you were a marker with five minutes. What's missing or unclear?", "Review"),
          ("TESTING.md", "Turn my feature list into a manual test script with expected results, mapped to the assignment's required topics.", "Structuring"),
          ("WORKLOG.md", "Read my reflection and point out any claims that aren't backed by evidence such as tests, commits or screenshots.", "Critique")]),
}

SUB_NOTES = {
 "01.1": "Gradle can't build yet (no `app` module). That's expected; test after 01.2.",
 "01.2": "First sync downloads a lot: allow several minutes. If prompted to upgrade AGP/Kotlin, choose **Don't upgrade** (the versions are pinned and compatible).",
 "04.4": "**Optional user step after this:** add photos and fonts from `ASSETS.md` (see substage 04.5 below). Real photos make every later screenshot better.",
 "05.3": "The first build after this creates `app/schemas/.../1.json`; it must be in this commit.",
 "08.2": "MainActivity becomes final here; the temporary signed-in placeholder from 07.4 is gone.",
 "17.6": "After this, no placeholder screens remain.",
 "18.1": "Database version 1 → 2: on next launch the old data is wiped and re-seeded automatically (sign in again). A new `app/schemas/.../2.json` appears; it belongs in this commit.",
}
